### PR TITLE
Andeutils

### PR DESCRIPTION
**Pull request by AnatoliyL2**
Andeutils are CLI programs from AndesauruxOS that i develop.
I think charch and listis are useful programs.
Charch is program that takes string and two characters.
Here's example:
$ charch Banan n b
Babab
Listis is program to work with lists

### CODE REVIEW

**Comment by sleepy-monax** [comment]
I'm open to merging core utilities into skift but they should be written using our library in C++

**Comment by AnatoliyL2** [comment]
> I'm open to merging core utilities into skift but they should be written using our library in C++

Is there package manager? 
If yes, i will add andeutils to repo of package manager

**Comment by sleepy-monax** [comment]
Also don't paste your random license into someone project it's rude

**Comment by AnatoliyL2** [comment]
> Also don't paste your random license into someone project it's rude

Ok, i will relicense andeuils under apache license 2.0

**Comment by sleepy-monax** [comment]
Skift is MIT

**Comment by sleepy-monax** [comment]
I only merge MIT code

**Pull request closed without merging**
