### PR TITLE
fix str used to check for double question mark equals token in vaev-js

### PR DESCRIPTION
**Pull request by JakeChampion**

### CODE REVIEW

**Comment by sleepy-monax** [comment]
Nice catch! 👍

**Comment by sleepy-monax** [comment]
Oops, I merged that too soon. This code worked as expected; we were preventing the compiler from interpreting `??=` as a trigraph. https://en.cppreference.com/w/cpp/language/operator_alternative

**Comment by JakeChampion** [comment]
Oh! Which version of c++ are we using? Trigraphs were removed in 17 I think

**Comment by sleepy-monax** [comment]
@JakeChampion C++23, but looks like Clang is still interpreting them

**Pull request merged**
